---

- name: Install base dependencies
  apt:
    update_cache: yes
    cache_valid_time: 360
    name: "{{ item }}"
  with_items:
    - unzip
    - curl
    - gnupg2
    - apt-transport-https
    - libgnutls28-dev
    - zlib1g-dev
    - libevent-dev
    - libicu-dev
    - libidn2-0-dev
    - libidn11-dev
    - librabbitmq-dev
    - libcurl4-gnutls-dev
    - libgnutls28-dev

- import_tasks: "{{ yml_file }}"
  with_items:
    - install-php
    - pecl
    - composer
  loop_control:
    loop_var: yml_file
