---

- name: pecl install amqp
  shell: pecl install amqp
  args:
    creates: "/usr/lib/php/20170718/amqp.so"

- name: pecl install raphf
  shell: pecl install raphf
  args:
    creates: "/usr/lib/php/20170718/raphf.so"

- name: pecl install propro
  shell: pecl install propro
  args:
    creates: "/usr/lib/php/20170718/propro.so"

- name: pecl install pecl_http
  shell: pecl install pecl_http
  args:
    creates: "/usr/lib/php/20170718/http.so"


- name: Add extensions to autoload
  lineinfile:
    create: yes
    path: "/etc/php/7.2/cli/conf.d/20-{{ item }}.ini"
    line: "extension={{ item }}.so"
    state: present
  with_items:
    - amqp
    - raphf
    - propro
    - http
